name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  
jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: Ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions: write-all

    # Steps run before the agent starts working
    steps:
      - name: Checkout apktool repository
        uses: actions/checkout@v6

      - name: Install MCP Server Dependencies
        run: |
          git clone https://github.com/extremerom/com_zhiliaoapp_musically.git tiktok
          cd tiktok
          rm -rf .git
          cd ..
      
          
      
